apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: tsy9kse66-go 
  janus-idp.io/tekton: tsy9kse66-go
  backstage.io/kubernetes-id: tsy9kse66-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: tsy9kse66-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  