apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: tsy9kse66-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: tsy9kse66-go 
  name: tsy9kse66-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: tsy9kse66-go 
